packages/input/src/chameleon-input.ts, packages/theme/base/input/index.ts, tsconfig.json
Adds in the ability to give a min and max value for number inputs
Closes #22
=> Bugfix: Chameleon Input

packages/input/src/chameleon-input.ts
binds the value of the input field to the element and closes #24
=> Bugfix: input

.storybook/stories/primary.stories.ts, Makefile, packages/card/README.md, packages/card/package-lock.json, packages/card/package.json, packages/card/src/chameleon-card.ts, packages/card/tsconfig.json, packages/theme/base/card/index.ts
=> adds the chameleon-card component

package-lock.json, package.json, packages/theme/base/input/index.ts
=> updates chameleon-input to prevent spilling outside of parent elements

packages/theme/base/button/index.ts
=> add pointer-events: none to prevent hover styles when chameleon-button is disabled

.storybook/stories/hero.stories.ts, Makefile, packages/hero/README.md, packages/hero/__tests__/chameleon-hero.test.ts, packages/hero/package-lock.json, packages/hero/package.json, packages/hero/src/chameleon-hero.ts, packages/hero/tsconfig.json, packages/theme/base/hero/index.ts, packages/theme/package-lock.json, rollup.config.js
Hero component that defaults to a CSS gradient background but also accepts a background image URL.
=> @chameleon hero

.storybook/stories/rice-ball-dessert.stories.ts, packages/rice-ball-dessert/README.md, packages/rice-ball-dessert/__tests__/chameleon-rice-ball-dessert.test.ts, packages/rice-ball-dessert/package-lock.json, packages/rice-ball-dessert/package.json, packages/rice-ball-dessert/src/chameleon-rice-ball-dessert-styles.ts, packages/rice-ball-dessert/src/chameleon-rice-ball-dessert.ts, packages/rice-ball-dessert/tsconfig.json
* `npm run dev`
* see `/?path=/story/rice-ball-dessert--basic`
You should find happiness.
=> feat(rice-ball-dessert): adds badly needed rice-ball-dessert component

.storybook/stories/hero.stories.ts, .storybook/stories/skeleton.stories.ts, Makefile, packages/hero/src/chameleon-hero.ts, packages/skeleton/README.md, packages/skeleton/__tests__/chameleon-skeleton.test.ts, packages/skeleton/package-lock.json, packages/skeleton/package.json, packages/skeleton/src/chameleon-skeleton.ts, packages/skeleton/tsconfig.json, packages/theme/base/skeleton/index.ts, rollup.config.js
Adding chameleon skeleton component.
=> @chameleon/skeleton

.storybook/stories/button.stories.ts, packages/button/src/chameleon-button.ts, packages/theme/base/button/index.ts, packages/toast/package-lock.json
Adds option of having icons placed to the left or right of a button. And also the option to have icon only displayed.
=> Enhancement - icons buttons

packages/textarea/src/chameleon-textarea.ts, yarn.lock
fixes bug where textarea wasn't updating with value Closes #130
=> BUGFIX: chameleon-textarea

packages/theme/base/toast/index.ts, packages/toast/src/chameleon-toast.ts
Changing this based upon feedback from UX. I'm putting slightly more space between the text and the close button. Also, the toast should now fade out instead of just disappearing. Additionally, on mobile, the toast is up higher so it doesn't conflict with the app bar.
=> Mm app bar mobile offset

packages/card-header/__tests__/chameleon-card-header.test.ts, packages/card-header/src/chameleon-card-header.ts, packages/card/__tests__/chameleon-card.test.ts, packages/card/src/chameleon-card.ts, packages/checkbox/__tests__/chameleon-checkbox.test.ts, packages/hero/__tests__/chameleon-hero.test.ts, packages/input/__tests__/chameleon-input.test.ts, packages/textarea/__tests__/chameleon-textarea.test.ts
this should add some testing coverage for checkbox, card, and textarea among various others
=> Add in testing coverage

packages/card-header/__tests__/chameleon-card-header.test.ts, packages/checkbox/__tests__/chameleon-checkbox.test.ts, packages/hero/__tests__/chameleon-hero.test.ts, packages/input/__tests__/chameleon-input.test.ts, packages/radio/__tests__/chameleon-radio.test.ts, packages/sheet/__tests__/chameleon-sheet.test.ts, packages/switch/__tests__/chameleon-switch.test.ts, packages/tabs/__tests__/chameleon-tabs.test.ts, packages/textarea/__tests__/chameleon-textarea.test.ts, packages/toast/__tests__/chameleon-toast.test.ts
gets testing coverage to 100%
closes #55 
closes #56
=> Testing coverage

package.json
=> run storybook on port 60000

.storybook/stories/loader.stories.ts, packages/loader/__tests__/chameleon-loader.test.ts, packages/loader/src/chameleon-loader-style.ts, packages/loader/src/chameleon-loader.ts, packages/loader/src/materialize-loader-style.ts
Adds an option for a spinner animation for chameleon-loader
closes #142
=> Spinner loader

packages/loader/src/chameleon-loader-style.ts, packages/loader/src/chameleon-loader.ts
I think I had missed a commit or something and the styles for the ellipsis loader were broken.
=> Fix styles for ellipsis loader

.storybook/stories/card.stories.ts, packages/card/src/chameleon-card-style.ts
https://github.com/MaritzSTL/chameleon/issues/144
=> removing max width

.storybook/stories/textarea.stories.ts, packages/textarea/src/chameleon-textarea-style.ts, packages/textarea/src/chameleon-textarea.ts
gives option to make textarea nonresizeable
=> added the parameter

.storybook/stories/chip.stories.ts, packages/chip/__tests__/chameleon-chip.test.ts, packages/chip/package.json, packages/chip/src/chameleon-chip-style.ts, packages/chip/src/chameleon-chip.ts
This chip will now dispatch an event whenever it's closed. You can check the console in storybook for the output of the event
=> Make Chip Closeable

.storybook/stories/multiselect.stories.ts, packages/multiselect/package.json, packages/multiselect/src/chameleon-multiselect-style.ts, packages/multiselect/src/chameleon-multiselect.ts
This will allow us to use multi-select for instant search.
closes #185
=> Dispatching Multi-select Search Event

packages/button/package.json, packages/button/src/chameleon-button-style.ts, packages/dialog/package.json, packages/paginator/package.json, packages/sheet/package.json
Adds in some configuration variables to make this work better with chameleon-date
=> Button Enhancements

.storybook/stories/select.stories.ts, packages/select/__tests__/chameleon-select.test.ts, packages/select/package.json, packages/select/src/chameleon-select-style.ts, packages/select/src/chameleon-select.ts
Just adds a label to the select component
=> adding the label

packages/button/src/chameleon-button-style.ts
=> default button size

.storybook/stories/table.stories.ts, packages/table/src/chameleon-table-style.ts, packages/table/src/chameleon-table.ts
- Tighten padding on detail rows.
- Add hidePagination property.
- Hide pagination if only 1 page is required.
=> Table updates

.storybook/stories/dialog.stories.ts, packages/dialog/src/chameleon-dialog-style.ts, packages/dialog/src/chameleon-dialog.ts
This is needed for recognition.
=> adding fullscreen option to chameleon-dialog

packages/textarea/src/chameleon-textarea-style.ts
Updates the textarea component to accept the font-family variable.
=> Update textarea font family

.storybook/stories/dialog.stories.ts, packages/dialog/__tests__/chameleon-dialog.test.ts, packages/dialog/src/chameleon-dialog-style.ts, packages/dialog/src/chameleon-dialog.ts
Recognition will need the ability to go back a step in the dialog.
=> Adding back icon to dialog and defaulting dialog to not open

packages/select/src/chameleon-select.ts
These seem like the most probable culprits.
=> removed console.logs

packages/multiselect/__tests__/chameleon-multiselect.test.ts, packages/multiselect/src/chameleon-multiselect-style.ts, packages/multiselect/src/chameleon-multiselect.ts
Right now the input field's min-height on the multiselect is set to 2.5rem but there are times when we want height to be 40px. Adding a variable to control this.
Label property exists but doesn't display. Added that in and had to restructure things slightly for styling.
Also added hover and active state color changes for label and input border.
=> multiselect min-height variable, label display, hover and active states

packages/input/src/chameleon-input-style.ts
=> Constrain height to 40px

.storybook/stories/sheet.stories.ts, packages/sheet/__tests__/chameleon-sheet.test.ts, packages/sheet/src/chameleon-sheet-style.ts, packages/sheet/src/chameleon-sheet.ts
Attaches and removes sheet from document body
Refactors sheet styles
Defaults sheet to open in storybook
=> Chameleon sheet ergonomics (improvement)

.storybook/stories/table.stories.ts, packages/table/src/chameleon-table-style.ts, packages/table/src/chameleon-table.ts, packages/table/types/index.ts
Adds the ability to pass classes to table ths and tds using the "headerClass" and "columnClass" properties. 
Also adds styling for left, center and right aligning text in the cells.
=> Table cell classes

.storybook/stories/select.stories.ts, .storybook/stories/timezone.stories.ts, __snapshots__/chameleon-date.md, packages/select/__tests__/chameleon-select.test.ts, packages/select/src/chameleon-select.ts, packages/timezone/src/chameleon-timezone.ts
Timezone component should now dispatch the `chameleon.timezone.input` event when something is selected
=> Chameleon timezone select event

.storybook/stories/sheet.stories.ts, __snapshots__/chameleon-select.md, __snapshots__/chameleon-sheet.md, packages/sheet/__tests__/chameleon-sheet.test.ts, packages/sheet/src/chameleon-sheet-style.ts, packages/sheet/src/chameleon-sheet.ts
* Adds in `open` method
* Adds in `close` method
* Adds in `updateSlot` method
* Removes `toggle-sheet` event
=> Update Chameleon Sheet

packages/date/__tests__/chameleon-date.test.ts, packages/date/src/chameleon-date-style.ts, packages/date/src/chameleon-date.ts
This creates a new property canDelete that defaults as true. If there is a date set, the user can delete it by clicking the close icon and it fires the same event, only with a null value. On setDate, I messed up the types, so guidance on that would be nice.
=> Sv 7288/delete date

.circleci/config.yml, package.json, packages/date/__tests__/chameleon-date.test.ts
Test coverage reporting is going to have to be broken until: https://github.com/open-wc/open-wc/pull/1556 gets merged
=> move up build step and comment out code coverage for now

.storybook/stories/skeleton.stories.ts, packages/hero/__tests__/chameleon-hero.test.ts, packages/skeleton/__tests__/chameleon-skeleton.test.ts, packages/skeleton/src/chameleon-skeleton-style.ts, packages/skeleton/src/chameleon-skeleton.ts
To test: go to storybook and set circle height to a value and set theme to "secondary" in order to see a circle instead of a rectangle.
=> new branch, adding optional circle skeleton

.storybook/stories/modal.stories.ts, packages/modal/src/chameleon-modal-style.ts
In integrating the modal with the app, I realized that I needed to adjust the header's grid for the title and I needed to adjust the right button for mobile.
=> Modal fixes
